// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initializeGarden(numFlowers int) *Garden {
	caretaker := GrowCaretaker()
	v := GrowFlowersRandom(numFlowers)
	garden := GrowGarden(caretaker, v)
	return garden
}
